# Generated by Django 4.2.9 on 2024-01-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeBridgeMinuteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('record', models.IntegerField()),
                ('battv_avg', models.CharField(max_length=255)),
                ('system_temp_avg', models.CharField(max_length=255)),
                ('temp_c_avg', models.CharField(max_length=255)),
                ('water_velocity', models.CharField(max_length=255)),
                ('water_column', models.CharField(max_length=255)),
                ('signal_quality', models.CharField(max_length=255)),
                ('water_discharge', models.CharField(max_length=255)),
            ],
        ),
    ]
